# Generated by Django 5.2 on 2025-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default='Текст відгуку за замовчуванням'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
